/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trigonometricofinal;



/**
 *
 * @author gisel
 */
public class Ventana extends javax.swing.JFrame {
    Calculador miCalculador = new Calculador();
    Trigonometrico miTrigonometrico = new Trigonometrico();
    float numero;
    int opcion;
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonSumar = new javax.swing.JButton();
        Ventanita = new javax.swing.JTextField();
        BotonIgual = new javax.swing.JButton();
        BotonResta = new javax.swing.JButton();
        BotonLimpiar = new javax.swing.JButton();
        BotonMultiplicar = new javax.swing.JButton();
        BotonDividir = new javax.swing.JButton();
        BotonSeno = new javax.swing.JButton();
        BotonTangente = new javax.swing.JButton();
        BotonCoseno = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonSumar.setBackground(new java.awt.Color(255, 255, 153));
        BotonSumar.setText("+");
        BotonSumar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSumarMouseClicked(evt);
            }
        });

        Ventanita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VentanitaMouseClicked(evt);
            }
        });

        BotonIgual.setText("=");
        BotonIgual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonIgualMouseClicked(evt);
            }
        });

        BotonResta.setBackground(new java.awt.Color(153, 153, 255));
        BotonResta.setText("-");
        BotonResta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRestaMouseClicked(evt);
            }
        });

        BotonLimpiar.setText("AC");
        BotonLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonLimpiarMouseClicked(evt);
            }
        });

        BotonMultiplicar.setBackground(new java.awt.Color(255, 204, 204));
        BotonMultiplicar.setText("x");
        BotonMultiplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMultiplicarMouseClicked(evt);
            }
        });

        BotonDividir.setBackground(new java.awt.Color(204, 102, 255));
        BotonDividir.setText("/");
        BotonDividir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonDividirMouseClicked(evt);
            }
        });

        BotonSeno.setText("Seno");
        BotonSeno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonSenoMouseClicked(evt);
            }
        });

        BotonTangente.setText("Tangente");
        BotonTangente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonTangenteMouseClicked(evt);
            }
        });

        BotonCoseno.setText("Coseno");
        BotonCoseno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCosenoMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 0, 255));
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("CALCULADORA ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ventanita, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BotonResta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BotonSumar, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BotonDividir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BotonMultiplicar, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                                .addGap(49, 49, 49)
                                .addComponent(BotonIgual)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonSeno, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(BotonCoseno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(BotonTangente)
                        .addGap(21, 21, 21))))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Ventanita, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonResta, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonSeno, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonCoseno, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonTangente, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    
    
    private void VentanitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentanitaMouseClicked
        // TODO add your handling code here:        
    }//GEN-LAST:event_VentanitaMouseClicked
    void GuardarOperando1(){
        numero=Float.valueOf(Ventanita.getText());
        miCalculador.operando1=numero;
        Ventanita.setText(" ");
    }
    
    void GuardarOperandoTrig(){
        numero=Float.valueOf(Ventanita.getText());
        miTrigonometrico.operando1=numero;        
        Ventanita.setText(" ");
    }
    
    private void BotonSumarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSumarMouseClicked
        
        opcion=1;
        GuardarOperando1();
    }//GEN-LAST:event_BotonSumarMouseClicked

    private void BotonIgualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonIgualMouseClicked
        // TODO add your handling code here:
        numero=Float.valueOf(Ventanita.getText()); 
        miCalculador.operando2=numero;
        
        switch (opcion){
            case 1: 
                miCalculador.Sumar();
                numero=miCalculador.resultado;
                break;
            case 2:
                miCalculador.Restar();
                numero=miCalculador.resultado;
                break;
            case 3:
                miCalculador.Multiplicar();
                numero=miCalculador.resultado;
                break;
            case 4:
                miCalculador.Dividir();
                numero=miCalculador.resultado;
                break;               
            
        }      
        Ventanita.setText(String.valueOf(numero));
    }//GEN-LAST:event_BotonIgualMouseClicked

    
    private void BotonRestaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRestaMouseClicked
        // TODO add your handling code here:
        opcion=2;
        GuardarOperando1();
    }//GEN-LAST:event_BotonRestaMouseClicked

    private void BotonLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonLimpiarMouseClicked
        // TODO add your handling code here:
        Ventanita.setText(" ");
    }//GEN-LAST:event_BotonLimpiarMouseClicked

    private void BotonMultiplicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMultiplicarMouseClicked
        // TODO add your handling code here:
        opcion=3;
        GuardarOperando1();
    }//GEN-LAST:event_BotonMultiplicarMouseClicked

    private void BotonDividirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonDividirMouseClicked
        // TODO add your handling code here:
        opcion=4;
        GuardarOperando1();
    }//GEN-LAST:event_BotonDividirMouseClicked

    private void BotonSenoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonSenoMouseClicked
                
        GuardarOperandoTrig();   
        miTrigonometrico.Seno();
        numero=miTrigonometrico.resultado;
        Ventanita.setText(String.valueOf(numero));        
    }//GEN-LAST:event_BotonSenoMouseClicked

    private void BotonCosenoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCosenoMouseClicked
               
        GuardarOperandoTrig();
        miTrigonometrico.Coseno();
        numero=miTrigonometrico.resultado;
        Ventanita.setText(String.valueOf(numero));
    }//GEN-LAST:event_BotonCosenoMouseClicked

    private void BotonTangenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonTangenteMouseClicked
        // TODO add your handling code here:
        GuardarOperandoTrig();
        miTrigonometrico.Tangent();
        numero=miTrigonometrico.resultado;
        Ventanita.setText(String.valueOf(numero));
    }//GEN-LAST:event_BotonTangenteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCoseno;
    private javax.swing.JButton BotonDividir;
    private javax.swing.JButton BotonIgual;
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JButton BotonMultiplicar;
    private javax.swing.JButton BotonResta;
    private javax.swing.JButton BotonSeno;
    private javax.swing.JButton BotonSumar;
    private javax.swing.JButton BotonTangente;
    private javax.swing.JTextField Ventanita;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
